trigger:
- master

variables:
  CMAKE_PREFIX_PATH : $(Build.BinariesDirectory)/Qt

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
      qt_host: linux
      qt_version: ''
      cmake_generator: ''
    windows:
      imageName: windows-2019
      qt_host: windows
      qt_version: win64_msvc2017_64
      cmake_generator: ''

pool:
  vmImage: $(imageName)

steps:
  - checkout: self
    submodules: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      cd $(Build.SourcesDirectory)
      python -m pip install aqtinstall
    displayName: 'Install aqtinstall'

  - script: |
      cd $(Build.SourcesDirectory)
      python -m aqt install --outputdir $(Build.BinariesDirectory)/Qt $(QtVersion) $(qt_host) desktop $(qt_version) -m qtcore qtxml qtnetwork qtwebsockets
    displayName: 'Install Qt $(QtVersion) for $(qt_host) $(qt_version)'

  - task: CMake@1
    inputs:
      cmakeArgs: '$(cmake_generator) ..'