trigger:
- master

variables:
  CMAKE_PREFIX_PATH : $(Build.BinariesDirectory)\\Qt

jobs:
- job: Windows
  strategy:
    matrix:
      windows:
        imageName: windows-2019
  pool:
    vmImage: $(imageName)
  steps:
    - template: ci/windows.yml
