#ifndef SIMPLEHTTPSERVER_DEFINES
#define SIMPLEHTTPSERVER_DEFINES

#include "qglobal.h"

#if defined BUILD_SIMPLEHTTPSERVER
#define SIMPLEHTTPSERVER_EXPORT Q_DECL_EXPORT
#else
#define SIMPLEHTTPSERVER_EXPORT Q_DECL_IMPORT 
#endif

#endif //SIMPLEHTTPSERVER_DEFINES