#ifndef QTHTTPSERVER_DEFINES
#define QTHTTPSERVER_DEFINES

#include "qglobal.h"

#if defined BUILD_QTHTTPSERVER
#define QTHTTPSERVER_EXPORT Q_DECL_EXPORT
#elif defined BUILD_QTHTTPSERVER_TESTS
#define QTHTTPSERVER_EXPORT
#else
#define QTHTTPSERVER_EXPORT Q_DECL_IMPORT 
#endif

#endif //QTHTTPSERVER_DEFINES